"""initial migration on server

Revision ID: d2c62d05172b
Revises: 
Create Date: 2025-10-06 19:00:57.802138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c62d05172b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('BLOG', 'PROJECT', name='contenttype'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homepage_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homepage_category_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_homepage_category_type'), ['type'], unique=False)

    op.create_table('homepage_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homepage_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homepage_tag_title'), ['title'], unique=True)

    op.create_table('homepage_technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('BACKEND', 'FRONTEND', 'DEVOPS', 'LANGUAGE', name='technologytype'), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homepage_technology', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homepage_technology_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_homepage_technology_type'), ['type'], unique=False)

    op.create_table('related_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('BLOG', 'PROJECT', name='contenttype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('BLOG', 'PROJECT', name='contenttype'), nullable=False),
    sa.CheckConstraint('NOT (source_id = target_id AND source_type = target_type)', name='ck_no_self_link'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', name='uq_related_content')
    )
    with op.batch_alter_table('related_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_related_content_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_related_content_target_type'), ['target_type'], unique=False)

    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('extract', sa.String(length=512), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('thumbnail', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['homepage_category.id'], name='fk_blog_post_category_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_visible'), ['visible'], unique=False)

    op.create_table('coding_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('subtitle', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', name='developmentstatus'), nullable=False),
    sa.Column('extract', sa.String(length=512), nullable=False),
    sa.Column('github_url', sa.String(length=128), nullable=True),
    sa.Column('deployment_url', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('featured_order', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['homepage_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('coding_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coding_project_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_project_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_project_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_project_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coding_project_visible'), ['visible'], unique=False)

    op.create_table('blogpost_tags',
    sa.Column('blogpost_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blogpost_id'], ['blog_post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['homepage_tag.id'], ),
    sa.PrimaryKeyConstraint('blogpost_id', 'tag_id')
    )
    op.create_table('blogpost_technologies',
    sa.Column('blogpost_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blogpost_id'], ['blog_post.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['homepage_technology.id'], ),
    sa.PrimaryKeyConstraint('blogpost_id', 'technology_id')
    )
    op.create_table('project_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', name='developmentstatus'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['coding_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_feature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_feature_project_id'), ['project_id'], unique=False)

    op.create_table('project_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('OVERVIEW', 'GOALS', 'IMPLEMENTATION', 'EXPLORATION', name='sectiontype'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['coding_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_section_project_id'), ['project_id'], unique=False)

    op.create_table('project_tags',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['coding_project.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['homepage_tag.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'tag_id')
    )
    op.create_table('project_technologies',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['coding_project.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['homepage_technology.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'technology_id')
    )
    op.create_table('related_projects',
    sa.Column('coding_project_id_1', sa.Integer(), nullable=False),
    sa.Column('coding_project_id_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coding_project_id_1'], ['coding_project.id'], ),
    sa.ForeignKeyConstraint(['coding_project_id_2'], ['coding_project.id'], ),
    sa.PrimaryKeyConstraint('coding_project_id_1', 'coding_project_id_2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_projects')
    op.drop_table('project_technologies')
    op.drop_table('project_tags')
    with op.batch_alter_table('project_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_section_project_id'))

    op.drop_table('project_section')
    with op.batch_alter_table('project_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_feature_project_id'))

    op.drop_table('project_feature')
    op.drop_table('blogpost_technologies')
    op.drop_table('blogpost_tags')
    with op.batch_alter_table('coding_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coding_project_visible'))
        batch_op.drop_index(batch_op.f('ix_coding_project_updated_at'))
        batch_op.drop_index(batch_op.f('ix_coding_project_status'))
        batch_op.drop_index(batch_op.f('ix_coding_project_slug'))
        batch_op.drop_index(batch_op.f('ix_coding_project_created_at'))
        batch_op.drop_index(batch_op.f('ix_coding_project_category_id'))

    op.drop_table('coding_project')
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_visible'))
        batch_op.drop_index(batch_op.f('ix_blog_post_updated_at'))
        batch_op.drop_index(batch_op.f('ix_blog_post_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_post_created_at'))
        batch_op.drop_index(batch_op.f('ix_blog_post_category_id'))

    op.drop_table('blog_post')
    with op.batch_alter_table('related_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_related_content_target_type'))
        batch_op.drop_index(batch_op.f('ix_related_content_source_type'))

    op.drop_table('related_content')
    with op.batch_alter_table('homepage_technology', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_technology_type'))
        batch_op.drop_index(batch_op.f('ix_homepage_technology_title'))

    op.drop_table('homepage_technology')
    with op.batch_alter_table('homepage_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_tag_title'))

    op.drop_table('homepage_tag')
    with op.batch_alter_table('homepage_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_category_type'))
        batch_op.drop_index(batch_op.f('ix_homepage_category_title'))

    op.drop_table('homepage_category')
    # ### end Alembic commands ###
